dist: trusty
sudo: required
services:
  - docker

language: node_js
node_js: lts/*

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install: yarn
script:
  - npm test
  - node_modules/.bin/vsce package
