dist: trusty
sudo: required
services:
  - docker

env:
  global:
    - secure: "FYlU9RgnKfVMAjH2AjbmWJIR7bPUocmwNKsFE/tJXBQNcbqsmpU+N0eW4/lr81NvFsmk2l5oQk/+uLKzdf6mzYz2gx9lacsC97w3Rg8pKRI26/LANT91PPpBi+Ehcx1hKToxpHpAw9AaoCT4m7pA1G3SjysCsd2anbyJq2negBz7eyVIJkIDSSYvPDRr3A6FRoIUKihx9NXuD1yNd0zL/IZW50BxDwscxSl7uoeHVPIiI+6ZSSSmhF6ggMeeIgrbDesnHmO81hPfrJPQiCnWb5L6XSTO5rkN5zBLrco5LIao6ch7I0wrAqhdTZettVMAgrAl38FYXSqo1WsUDYXxpacgdzq2QahkG2NJp3A1ktKPqgbfDJb2XwZ72/pXX+Ap89EaEAhROPdKAMI8X5UmnLazFRqw7hTCg9gNDyPxKa/AbTSpMSEOgVBUjgeBtS0ovjGfpHjbrg6Eldq21vVYdqhyFX00Hozta2ZjnYjDS2gQuAhFUqASCr+PF4PdUY3VFKfLlE/fkQfh2EvWS2QEaqhnu+6mnky0xgL+oH33AoJehJ84FPPjaqFKFvstIRbfVEqq8Yttj3UCVcP0dnzezVgEmKA4bU7/+N4zgNvaqTnhiCOvHGY5tGy3Lar0Lm4eMiXjjQyFxu7PQ7vWuvZ8r1/plY6aQFukDmOKxQlKuv0="

language: node_js
node_js: lts/*

install: npm install
script:
  - npm test
  - node_modules/.bin/vsce package

deploy:
  - provider: script
    script: vsce publish -p $VS_TOKEN
    skip_cleanup: true
    on:
      repo: fkrull/vscode-gtk-dark-titlebar
      tags: true
      condition: $TRAVIS_TAG =~ ^release-
